### ISSUE TITLE
Convert from Vacuum to air wavelengths

### ISSUE THREAD

**Issue by EduardoCristo** [bmorris3/expecto#3]
Hi!
I tried to use the get_spectrum function with vacuum=False to perform the conversion from vacuum to air wavelengths .  I have the following error after this:

  File ".../python3.8/site-packages/specutils/spectra/spectrum1d.py", line 302, in __init__
    raise ValueError('Spectral axis must be strictly increasing or decreasing.')
ValueError: Spectral axis must be strictly increasing or decreasing.

I guess that something happens during the conversion itself, can you check this please?

Cheers,
Eduardo.

**Comment by bmorris3** [comment]
Hi @EduardoCristo, thanks for this note! I've fixed the `get_spectrum` function so that this works again. I've released a bugfix for `expecto`, so you can get a working version with:
```
pip install -U expecto
```
Thanks 😄
